version: '3.8'
services:
  frontend:
    container_name: frontend
    build: ./positive-health-int-team-2-frontend
    volumes:
      - ./positive-health-int-team-2-frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    networks:
      - positive-health
  map-service:
    container_name: map-service
    build: ./positive-health-int-team-2-backend/map-service
    volumes:
      - ./positive-health-int-team-2-backend/map-service/code:/usr/src/app
    networks:
      - positive-health
    ports:
      - "3019:3019"
    working_dir: /usr/src/app
    command: npm run dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - map-db
  userprofile-service:
    container_name: userprofile-service
    build: ./positive-health-int-team-2-backend/userprofile-service
    volumes:
      - ./positive-health-int-team-2-backend/userprofile-service/code:/usr/src/app
    networks:
      - positive-health
    ports:
      - "3018:3018"
    working_dir: /usr/src/app
    command: npm run dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - userprofile-db
  activities-service:
    container_name: activities-service
    build: ./positive-health-int-team-2-backend/activities-service
    volumes:
      - ./positive-health-int-team-2-backend/activities-service/code:/usr/src/app
    networks:
      - positive-health
    ports:
      - "3015:3015"
    working_dir: /usr/src/app
    command: npm run dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - activities-db
  authentication-service:
    container_name: authentication-service
    build: ./positive-health-int-team-2-backend/authentication-service
    volumes:
      - ./positive-health-int-team-2-backend/authentication-service/code:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - positive-health
    ports:
      - "3020:3020"
    working_dir: /usr/src/app
    command: npm run dev
    environment:
      - CHOKIDAR_USEPOLLING=true
  friends-service:
    container_name: friends-service
    build: ./positive-health-int-team-2-backend/friends-service
    volumes:
      - ./positive-health-int-team-2-backend/friends-service/code:/usr/src/app
    networks:
      - positive-health
    ports:
      - "3021:3021"
    working_dir: /usr/src/app
    command: npm run dev
    environment:
      - CHOKIDAR_USEPOLLING=true
  chat-service:
    container_name: chat-service
    build: ./positive-health-int-team-2-backend/chat-service
    volumes:
      - ./positive-health-int-team-2-backend/chat-service/code:/usr/src/app
    networks:
      - positive-health
    ports:
      - "3090:3090"
    working_dir: /usr/src/app
    command: npm run dev
    environment:
      - CHOKIDAR_USEPOLLING=true
  api-gateway:
    container_name: api-gateway
    build: ./positive-health-int-team-2-backend/api-gateway
    volumes:
      - ./positive-health-int-team-2-backend/api-gateway/code:/usr/src/app
    networks:
      - positive-health
    ports:
      - "3025:3025"
    working_dir: /usr/src/app
    command: npm run dev
    environment:
      - CHOKIDAR_USEPOLLING=true
  chat-db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: chat_db
      MYSQL_USER: example123
      MYSQL_PASSWORD: example123
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - '3304:3306'
    volumes:
      - chat-db:/var/lib/mysql
    networks:
      - positive-health
  friends-db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: friends_db
      MYSQL_USER: example123
      MYSQL_PASSWORD: example123
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - '3305:3306'
    volumes:
      - friends-db:/var/lib/mysql
    networks:
      - positive-health
  activities-db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: activities_db
      MYSQL_USER: activity123
      MYSQL_PASSWORD: activity123123
      MYSQL_ROOT_PASSWORD: activity123123
    ports:
      - '3307:3306'
    volumes:
      - activities-db:/var/lib/mysql
    networks:
      - positive-health
  appointments-db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: appointments_db
      MYSQL_USER: activity123
      MYSQL_PASSWORD: activity123123
      MYSQL_ROOT_PASSWORD: activity123123
    ports:
      - '3308:3306'
    volumes:
      - appointments-db:/var/lib/mysql
    networks:
      - positive-health
  authentication-db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: authentication_db
      MYSQL_USER: example
      MYSQL_PASSWORD: example
      MYSQL_ROOT_PASSWORD: example
    ports:
      - '3309:3306'
    volumes:
      - authentication-db:/var/lib/mysql
    networks:
      - positive-health
  map-db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: map-db
      MYSQL_USER: activity123
      MYSQL_PASSWORD: activity123123
      MYSQL_ROOT_PASSWORD: activity123123
    ports:
      - '3302:3306'
    volumes:
      - map-db:/var/lib/mysql
    networks:
      - positive-health
  userprofile-db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: userprofile_db
      MYSQL_USER: activity123
      MYSQL_PASSWORD: activity123123
      MYSQL_ROOT_PASSWORD: activity123123
    ports:
      - '3303:3306'
    volumes:
      - userprofile-db:/var/lib/mysql
    networks:
      - positive-health
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: activities-db
      PMA_PORT: 3306
      PMA_USER: activity123
      PMA_PASSWORD: activity123123
    ports:
      - '8080:80'
    depends_on:
      - activities-db
    networks:
      - positive-health
networks:
  positive-health:
    driver: bridge
volumes:
  activities-db:
  appointments-db:
  authentication-db:
  map-db:
  userprofile-db:
  friends-db:
  chat-db:
