version: '3.8'
services:
  activities-service:
    container_name: activities-service
    build: ./activities-service
    volumes:
      - ./activities-service/code:/usr/src/app
    networks:
      - positive-health
    ports:
      - "3015:3015"
    working_dir: /usr/src/app
    command: npm run dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - activities-db
  appointments:
    container_name: sample-service
    build: ./sample-service
    volumes:
      - ./sample-service/code:/usr/src/app
    networks:
      - positive-health
    ports:
      - "3010:3010"
    working_dir: /usr/src/app
    command: npm run dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - appointments-db
  api-gateway:
    container_name: api-gateway
    build: ./api-gateway
    volumes:
      - ./api-gateway/code:/usr/src/app
    networks:
      - positive-health
    ports:
      - "3025:3025"
    working_dir: /usr/src/app
    command: npm run dev
    environment:
      - CHOKIDAR_USEPOLLING=true
  authentication-service:
    container_name: authentication-service
    build: ./authentication-service
    volumes:
      - ./authentication-service/code:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - positive-health
    ports:
      - "3020:3020"
    working_dir: /usr/src/app
    command: npm run dev
    environment:
      - CHOKIDAR_USEPOLLING=true
  activities-db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: activities_db
      MYSQL_USER: activity123
      MYSQL_PASSWORD: activity123123
      MYSQL_ROOT_PASSWORD: activity123123
    ports:
      - '3307:3306'
    volumes:
      - activities-db:/var/lib/mysql
    networks:
      - positive-health
  appointments-db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: appointments_db
      MYSQL_USER: activity123
      MYSQL_PASSWORD: activity123123
      MYSQL_ROOT_PASSWORD: activity123123
    ports:
      - '3308:3306'
    volumes:
      - appointments-db:/var/lib/mysql
    networks:
      - positive-health
  authentication-db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: authentication_db
      MYSQL_USER: example
      MYSQL_PASSWORD: example
      MYSQL_ROOT_PASSWORD: example
    ports:
      - '3309:3306'
    volumes:
      - authentication-db:/var/lib/mysql
    networks:
      - positive-health
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: authentication-db
      PMA_PORT: 3306
      PMA_USER: example
      PMA_PASSWORD: example
    ports:
      - '8080:80'
    depends_on:
      - authentication-db
    networks:
      - positive-health
networks:
  positive-health:
    driver: bridge
volumes:
  activities-db:
  appointments-db:
  authentication-db:
