version: '3.8'
services:
  activities-service:
    container_name: activities-service
    build: ./activities-service
    volumes:
      - ./activities-service/code:/usr/src/app
    networks:
      - positive-health
    ports:
      - "3015:3015"
    working_dir: /usr/src/app
    command: npm run dev
    environment:
      - CHOKIDAR_USEPOLLING=true

  appointments:
    container_name: sample-service
    build: ./sample-service
    volumes:
      - ./sample-service/code:/usr/src/app
    networks:
      - positive-health
    ports:
      - "3010:3010"
    working_dir: /usr/src/app
    command: npm run dev
    environment:
      - CHOKIDAR_USEPOLLING=true

networks:
  positive-health:
    driver: bridge