version: '3.8'
services:
  appointments:
    container_name: sample-service
    build: ./sample-service
    volumes:
      - ./sample-service/code:/usr/src/app
    networks:
      - positive-health
    ports:
      - "3010:3010"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"
networks:
  positive-health:
    driver: bridge