name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Go to the backend
      run: cd positive-health-int-team-2-backend
    - name: Check the path
      run: echo pwd  
    - name: Build the Docker image
      run: docker-compose up
