name: GitHub Actions Demo
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./positive-health-int-team-2-frontend
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npx playwright install
      - name: Run Tests
        run: npx vitest
  run-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./positive-health-int-team-2-frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run-docker-compose:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3         
    - uses: isbang/compose-action@v1.5.1
      with:
        compose-file: "./positive-health-int-team-2-backend/docker-compose.yml"
